services:
  redis:
    image: redis:8.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - monorepo-network

  postgres:
    image: postgres:16.9-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - monorepo-network

  websocket-server:
    image: jakobklippel/loopstack-websocket-server:latest
    pull_policy: always
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - APP_PORT=${APP_PORT:-8001}
      - CORS_ORIGIN=${WS_PORT:-localhost}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - LOCAL_MODE=${ENABLE_LOCAL_MODE:-false}
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - monorepo-network

networks:
  monorepo-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local
